### ISSUE TITLE
Aspects and SocketRocket

### ISSUE THREAD

**Issue by diogoAntunes** [lqd-io/liquid-sdk-ios#19]
Im getting this error after updating liquid using cocoapods:
"SRWebSocket.h" not found.

Apparently SocketRocket and Aspects are not being included.

**Comment by miguelcma** [comment]
Hi @diogoAntunes! It should work out-of-the-box, as SocketRocket and Aspects are defined as dependencies. Just let me check what's going on, probably a misconfiguration of Podfile.

**Comment by diogoAntunes** [comment]
Hey @miguelcma, not working for me :( I had to target a older version of Liquid.

**Comment by miguelcma** [comment]
Fixed at [v2.3.2](https://github.com/lqd-io/liquid-sdk-ios/releases/tag/v2.3.2)

**Comment by hellojeffy** [comment]
@miguelcma I'm still getting the "SRWebSocket.h" not found when using liquid with cocoapods and swift (importing Liquid/Liquid.h in bridging header), version 2.3.2

**Comment by diogoAntunes** [comment]
I'm still getting it on version 2.3.4
